// ---------------------------------------------------------------------------
// Classname helper — merges conditional classes and resolves Tailwind
// conflicts (e.g. cn("px-2", condition && "px-4") keeps only "px-4").
//
// `extendTailwindMerge` teaches tailwind-merge about the custom color and
// text-style names from the Color/Font library (app/globals.css +
// styles/tokens/*.css) — e.g. that `text-label-sm` and `text-label-md` are
// both font-size utilities (so one overrides the other), and that
// `text-primary` and `text-foreground` are both text-color utilities.
// Without this, tailwind-merge doesn't recognize these custom theme names
// and can't correctly resolve conflicts between them.
// ---------------------------------------------------------------------------
import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        // Primitives — every ramp step
        "brand-25",
        "brand-50",
        "brand-100",
        "brand-200",
        "brand-300",
        "brand-400",
        "brand-500",
        "brand-600",
        "brand-700",
        "brand-800",
        "brand-900",
        "brand-950",
        "secondary-25",
        "secondary-50",
        "secondary-100",
        "secondary-200",
        "secondary-300",
        "secondary-400",
        "secondary-500",
        "secondary-600",
        "secondary-700",
        "secondary-800",
        "secondary-900",
        "secondary-950",
        "gray-25",
        "gray-50",
        "gray-100",
        "gray-200",
        "gray-300",
        "gray-400",
        "gray-500",
        "gray-600",
        "gray-700",
        "gray-800",
        "gray-900",
        "gray-950",
        "success-50",
        "success-100",
        "success-300",
        "success-500",
        "success-700",
        "success-900",
        "warning-50",
        "warning-100",
        "warning-300",
        "warning-500",
        "warning-700",
        "warning-900",
        "error-50",
        "error-100",
        "error-300",
        "error-500",
        "error-700",
        "error-900",
        "info-50",
        "info-100",
        "info-300",
        "info-500",
        "info-700",
        "info-900",
        // Semantic — Figma's exact "02 · Color Semantic" names
        "background-primary",
        "background-secondary",
        "background-inverse",
        "surface-primary",
        "surface-secondary",
        "surface-brand",
        "surface-brand-2",
        "surface-success",
        "surface-warning",
        "surface-error",
        "surface-info",
        "surface-pressed",
        "text-primary",
        "text-secondary",
        "text-tertiary",
        "text-disabled",
        "text-inverse",
        "text-on-brand",
        "text-on-secondary",
        "text-success",
        "text-warning",
        "text-error",
        "text-info",
        "border-primary",
        "border-secondary",
        "border-success",
        "border-warning",
        "border-error",
        "border-info",
        "icon-primary",
        "icon-brand",
        "icon-secondary",
        "icon-disabled",
        "brand-default",
        "brand-subtle",
        "secondary-default",
        "secondary-subtle",
        "success-default",
        "warning-default",
        "error-default",
        "info-default",
        // App aliases — what components actually use day to day
        "primary",
        "primary-hover",
        "primary-pressed",
        "brand",
        "brand-hover",
        "brand-pressed",
        "brand-ink",
        "secondary",
        "secondary-hover",
        "secondary-pressed",
        "on-secondary",
        "foreground",
        "foreground-muted",
        "foreground-subtle",
        "foreground-disabled",
        "foreground-inverse",
        "background",
        "background-subtle",
        "surface",
        "surface-dark",
        "surface-dark-deep",
        "surface-accent",
        "border",
        "border-subtle",
        "border-focus",
        "success",
        "success-bg",
        "success-text",
        "warning",
        "warning-bg",
        "warning-text",
        "error",
        "error-bg",
        "error-text",
        "info",
        "info-bg",
        "info-text",
        // Component tokens — Button/Input, from "06 · Component Tokens"
        "button-primary-bg",
        "button-primary-bg-hover",
        "button-primary-bg-pressed",
        "button-primary-text",
        "button-secondary-bg",
        "button-secondary-bg-hover",
        "button-secondary-bg-pressed",
        "button-secondary-text",
        "button-outline-border",
        "button-outline-text",
        "button-outline-bg-hover",
        "button-outline-bg-pressed",
        "button-ghost-text",
        "button-ghost-bg-hover",
        "button-ghost-bg-pressed",
        "input-bg",
        "input-bg-disabled",
        "input-border",
        "input-border-focus",
        "input-border-error",
        "input-border-disabled",
        "input-text",
        "input-text-placeholder",
        "input-text-disabled",
        "input-label",
        "input-helper-text",
        "input-helper-text-error",
      ],
      text: [
        "display-2xl",
        "display-xl",
        "display-lg",
        "heading-1",
        "heading-2",
        "heading-3",
        "heading-4",
        "heading-5",
        "body-lg",
        "body-md",
        "body-sm",
        "label-md",
        "label-sm",
        "caption-md",
        "code-md",
        "display-wordmark",
        "display-jumbo",
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
